#!/bin/sh

err() {
    echo "$0: $1" >&2
    exit 1
}

check_dep() {
    command -v "$1" > /dev/null || err "$1 is required: $2"
}

check_dep dmenu   https://tools.suckless.org/dmenu
check_dep xdotool https://github.com/jordansissel/xdotool
check_dep xprop   https://gitlab.freedesktop.org/xorg/app/xprop

# dmenu command
[ -z "$DMENU" ] && DMENU='dmenu -i -l 10 -p Windows'

get_windows_ids() {
    xprop -root _NET_CLIENT_LIST |
        sed 's/^.\+# //; s/, \+/\n/g' | sort | uniq
}

get_window_name() {
    xprop -id "$1" WM_NAME | sed 's/^.\+ = //; s/^"//; s/"$//'
}

# Get windows in format "$num $id $name"
get_windows() {
    get_windows_ids | while read -r id; do
        echo "$id $(get_window_name "$id")"
    done | nl -w 1 -s ' '
}

get_window_id() {
    cut -d ' ' -f 2
}

get_windows_menu() {
    cut -d ' ' -f '1,3-' | column -t -l 2
}

get_num_from_selection() {
    echo "$1" | cut -d ' ' -f 1
}

get_selected_window() {
    grep "^$(get_num_from_selection "$1") "
}

focus_window() {
    xdotool windowactivate "$1"
}

windows="$(get_windows)"

selection="$(echo "$windows" | get_windows_menu | $DMENU)"
[ -z "$selection" ] && exit 0

focus_window "$(echo "$windows" | get_selected_window "$selection" | get_window_id)"
